### ISSUE TITLE
ipythonblocks not rendering on github.com

### ISSUE THREAD

**Issue by jiffyclub** [ipython/nbconvert#204]
With GitHub's [new notebook rendering](https://github.com/blog/1995-github-jupyter-notebooks-3) [ipythonblocks](https://github.com/jiffyclub/ipythonblocks) tables aren't rendered correctly as they are in nbviewer. Examples:

GitHub: https://github.com/jiffyclub/ipythonblocks/blob/master/demos/starry_night_to_text.ipynb
nbviewer: http://nbviewer.ipython.org/github/jiffyclub/ipythonblocks/blob/master/demos/starry_night_to_text.ipynb

Looking at the HTML it looks like GitHub is stripping out `style` tags and attributes, and `id` attributes:

GitHub:
![screenshot 2015-05-07 13 10 15](https://cloud.githubusercontent.com/assets/920492/7524972/6e50a876-f4ba-11e4-80bf-7f35bc63bd95.png)

nbviewer:
![screenshot 2015-05-07 13 09 28](https://cloud.githubusercontent.com/assets/920492/7524955/52148a6a-f4ba-11e4-8f11-7dbf0bebd226.png)

**Comment by minrk** [comment]
Can you reopen at https://github.com/jupyter/nbviewer? That's where we are going to track problems with the GitHub deployment. This repo is old and dead. I'll disable issues here once it's moved over.

**Comment by jiffyclub** [comment]
Done: https://github.com/jupyter/nbviewer/issues/450

**Comment by minrk** [comment]
Thanks
